on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to  build and publish docker images
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the output times
        run: echo "The image name is not cool"
